
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, MapPin, Lightbulb, Trophy, AlertCircle, Sparkles, Mic, MicOff, MessageSquareText } from 'lucide-react';
import { AnalysisResult, RiskLevel } from '../types';
import RiskBadge from './RiskBadge';
import VoiceAdvisor from './VoiceAdvisor';

interface StudentViewProps {
  analysis: AnalysisResult[];
}

const StudentView: React.FC<StudentViewProps> = ({ analysis }) => {
  const [searchId, setSearchId] = useState('');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [hasSearched, setHasSearched] = useState(false);
  const [showVoice, setShowVoice] = useState(false);

  const handleSearch = () => {
    if (!searchId.trim()) return;
    const found = analysis.find(a => a.studentId.toLowerCase() === searchId.toLowerCase());
    setResult(found || null);
    setHasSearched(true);
  };

  return (
    <div className="max-w-4xl mx-auto px-6 py-16">
      <div className="text-center mb-16 space-y-4">
        <h2 className="text-4xl font-black text-slate-900 tracking-tight">Student Portal</h2>
        <p className="text-slate-500 text-lg font-medium max-w-xl mx-auto">
          Insights generated by AI to help you navigate your academic journey.
        </p>
      </div>

      <div className="bg-white/90 backdrop-blur-xl p-10 rounded-[3rem] shadow-[0_20px_50px_rgba(0,0,0,0.05)] border border-slate-200/50 relative overflow-hidden">
        
        {/* Floating Voice Toggle */}
        <button 
          onClick={() => setShowVoice(!showVoice)}
          className={`absolute top-6 right-6 p-3 rounded-2xl transition-all shadow-lg flex items-center gap-2 font-bold text-xs ${showVoice ? 'bg-rose-500 text-white shadow-rose-200 scale-105' : 'bg-indigo-600 text-white shadow-indigo-200'}`}
        >
          {showVoice ? <><MicOff size={16}/> Close Advisor</> : <><Mic size={16}/> Talk to Advisor</>}
        </button>

        <AnimatePresence mode="wait">
          {showVoice ? (
            <motion.div 
              key="voice"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className="py-10"
            >
              <VoiceAdvisor studentInfo={result ? `Matric: ${result.studentId}, Risk: ${result.riskLevel}, Feedback: ${result.rootCause}` : undefined} />
            </motion.div>
          ) : (
            <motion.div 
              key="portal"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <div className="max-w-md mx-auto mb-12">
                <label className="block text-center text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-4">
                  Identify Yourself
                </label>
                <div className="relative group">
                  <input 
                    type="text" 
                    value={searchId}
                    onChange={(e) => {
                      setSearchId(e.target.value);
                      if (hasSearched) setHasSearched(false);
                    }}
                    onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                    placeholder="Enter Matric Number (e.g. 2023-CS-1014)"
                    className="w-full h-14 pl-6 pr-14 rounded-2xl bg-slate-100/50 border-transparent focus:bg-white focus:ring-4 focus:ring-indigo-500/10 focus:border-indigo-500 font-bold transition-all text-slate-800 placeholder:text-slate-400 shadow-inner"
                  />
                  <button 
                    onClick={handleSearch}
                    className="absolute right-2 top-2 h-10 w-10 flex items-center justify-center bg-indigo-600 text-white rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 active:scale-90 transition-all"
                  >
                    <Search size={18} strokeWidth={3} />
                  </button>
                </div>
              </div>

              <AnimatePresence mode="wait">
                {hasSearched && result ? (
                  <motion.div 
                    key="result"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="space-y-8"
                  >
                    <div className="flex flex-col items-center p-8 bg-indigo-50/30 rounded-[2rem] border border-indigo-100/50 relative overflow-hidden">
                      <div className="absolute top-0 right-0 p-8 opacity-5 text-indigo-500">
                        <Sparkles size={80} />
                      </div>
                      
                      <span className="text-[10px] font-black text-indigo-500 uppercase tracking-[0.3em] mb-2">Authenticated View</span>
                      <h4 className="text-2xl font-black text-slate-900 mb-4">{result.studentId}</h4>
                      <RiskBadge level={result.riskLevel} />
                      
                      <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6 w-full max-w-2xl">
                        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col gap-3">
                          <div className="flex items-center gap-2 text-indigo-600">
                            <Lightbulb size={18} strokeWidth={2.5} />
                            <span className="text-[10px] font-black uppercase tracking-widest">Feedback</span>
                          </div>
                          <p className="text-slate-600 text-sm font-medium leading-relaxed italic">
                            "{result.rootCause}"
                          </p>
                        </div>
                        
                        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col gap-3">
                          <div className="flex items-center gap-2 text-emerald-600">
                            <MapPin size={18} strokeWidth={2.5} />
                            <span className="text-[10px] font-black uppercase tracking-widest">Success Roadmap</span>
                          </div>
                          <p className="text-slate-600 text-sm font-medium leading-relaxed">
                            {result.interventionStrategy}
                          </p>
                        </div>
                      </div>
                    </div>

                    {result.riskLevel === RiskLevel.ON_TRACK && (
                      <motion.div 
                        initial={{ y: 20, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ delay: 0.2 }}
                        className="p-6 bg-gradient-to-r from-emerald-50 to-teal-50 border border-emerald-100 rounded-3xl flex items-center gap-5 shadow-sm"
                      >
                        <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-emerald-500 shadow-md">
                          <Trophy size={24} />
                        </div>
                        <div>
                          <h4 className="font-extrabold text-emerald-900 text-sm">Outstanding Performance!</h4>
                          <p className="text-emerald-700 text-xs font-medium">Your current metrics indicate high engagement and academic stability.</p>
                        </div>
                      </motion.div>
                    )}
                  </motion.div>
                ) : hasSearched ? (
                  <motion.div 
                    key="not-found"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-center py-16"
                  >
                    <div className="w-20 h-20 bg-rose-50 text-rose-300 rounded-full flex items-center justify-center mx-auto mb-6">
                      <AlertCircle size={40} />
                    </div>
                    <h3 className="text-xl font-extrabold text-slate-900">Identity Unavailable</h3>
                    <p className="text-slate-400 text-sm font-medium mt-2 max-w-xs mx-auto leading-relaxed">
                      The Matric Number <b>"{searchId}"</b> was not found in the latest success engine report.
                    </p>
                  </motion.div>
                ) : (
                  <motion.div 
                    key="idle"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-center py-20 space-y-4"
                  >
                    <div className="text-slate-200">
                      <MessageSquareText size={48} className="mx-auto opacity-20" />
                    </div>
                    <p className="text-slate-300 font-bold uppercase tracking-[0.2em] text-xs">
                      Waiting for lookup or voice activation
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default StudentView;
